WB0573SK0/DEVELOPER/BS3/RubyOnRails/full/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'dashboard#analytics'
  get 'dashboards/dashboard-social',
      to: 'dashboard#social',
      as: :dashboard_social

  # Smartadmin intel
  get 'smartadmin_intel/app_layouts',
      to: 'smartadmin_intel#app_layouts',
      as: :smartadmin_intel_app_layouts
  get 'smartadmin_intel/app_settings',
      to: 'smartadmin_intel#app_settings',
      as: :smartadmin_intel_app_settings
  get 'smartadmin_intel/prebuilt_skins',
      to: 'smartadmin_intel#prebuilt_skins',
      as: :smartadmin_intel_prebuilt_skins
  get 'outlook/inbox', to: 'outlook#inbox', as: :outlook_inbox

  # AJAX
  get 'ajax/email_compose', to: 'ajax#email_compose', as: :ajax_email_compose
  get 'ajax/email_list', to: 'ajax#email_list', as: :ajax_email_list
  get 'ajax/email_opened', to: 'ajax#email_opened', as: :ajax_email_opened
  get 'ajax/email_reply', to: 'ajax#email_reply', as: :ajax_email_reply
  get 'ajax/demo_widget', to: 'ajax#demo_widget', as: :ajax_demo_widget
  get 'ajax/data_list.json', to: 'ajax#data_list', as: :ajax_data_list
  get 'ajax/notify_mail', to: 'ajax#notify_mail', as: :ajax_notify_mail
  get 'ajax/notify_notifications',
      to: 'ajax#notify_notifications',
      as: :ajax_notify_notifications
  get 'ajax/notify_tasks', to: 'ajax#notify_tasks', as: :ajax_notify_tasks

  # Graphs
  get 'graphs/flot_chart', to: 'graphs#flot_chart', as: :graphs_flot_chart
  get 'graphs/morris_charts',
      to: 'graphs#morris_charts',
      as: :graphs_morris_charts
  get 'graphs/sparklines', to: 'graphs#sparklines', as: :graphs_sparklines
  get 'graphs/easy_pie_charts',
      to: 'graphs#easy_pie_charts',
      as: :graphs_easy_pie_charts
  get 'graphs/dygraphs', to: 'graphs#dygraphs', as: :graphs_dygraphs
  get 'graphs/chart_js', to: 'graphs#chart_js', as: :graphs_chart_js
  get 'graphs/highchart_table',
      to: 'graphs#highchart_table',
      as: :graphs_highchart_table

  # Tables
  get 'tables/normal_tables',
      to: 'tables#normal_tables',
      as: :tables_normal_tables
  get 'tables/data_tables', to: 'tables#data_tables', as: :tables_data_tables
  get 'tables/jquery_grid', to: 'tables#jquery_grid', as: :tables_jquery_grid

  # Forms
  get 'forms/smart_form_elements',
      to: 'forms#smart_form_elements',
      as: :forms_smart_form_elements
  get 'forms/smart_form_layouts',
      to: 'forms#smart_form_layouts',
      as: :forms_smart_form_layouts
  get 'forms/smart_form_validations',
      to: 'forms#smart_form_validations',
      as: :forms_smart_form_validations
  get 'forms/bootstrap_form_elements',
      to: 'forms#bootstrap_form_elements',
      as: :forms_bootstrap_form_elements
  get 'forms/bootstrap_form_validation',
      to: 'forms#bootstrap_form_validation',
      as: :forms_bootstrap_form_validation
  get 'forms/form_plugins', to: 'forms#form_plugins', as: :forms_form_plugins
  get 'forms/wizards', to: 'forms#wizards', as: :forms_wizards
  get 'forms/bootstrap_editors',
      to: 'forms#bootstrap_editors',
      as: :forms_bootstrap_editors
  get 'forms/dropzone', to: 'forms#dropzone', as: :forms_dropzone
  get 'forms/image_cropping',
      to: 'forms#image_cropping',
      as: :forms_image_cropping
  get 'forms/ck_editor', to: 'forms#ck_editor', as: :forms_ck_editor

  # UI Elements
  get 'ui_elements/general_elements',
      to: 'ui_elements#general_elements',
      as: :ui_elements_general_elements
  get 'ui_elements/buttons', to: 'ui_elements#buttons', as: :ui_elements_buttons
  get 'ui_elements/icons/font_awesome',
      to: 'ui_elements#icons_font_awesome',
      as: :ui_elements_icons_font_awesome
  get 'ui_elements/icons/glyph_icons',
      to: 'ui_elements#icons_glyph_icons',
      as: :ui_elements_icons_glyph_icons
  get 'ui_elements/icons/flags',
      to: 'ui_elements#icons_flags',
      as: :ui_elements_icons_flags
  get 'ui_elements/grid', to: 'ui_elements#grid', as: :ui_elements_grid
  get 'ui_elements/tree_view',
      to: 'ui_elements#tree_view',
      as: :ui_elements_tree_view
  get 'ui_elements/nestable_lists',
      to: 'ui_elements#nestable_lists',
      as: :ui_elements_nestable_lists
  get 'ui_elements/jquery_ui',
      to: 'ui_elements#jquery_ui',
      as: :ui_elements_jquery_ui
  get 'ui_elements/typography',
      to: 'ui_elements#typography',
      as: :ui_elements_typography

  # Widgets
  get 'widgets/', to: 'widgets#index', as: :widgets

  # Cool Features
  get 'cool_features/calendar',
      to: 'cool_features#calendar',
      as: :cool_features_calendar
  get 'cool_features/gmap_skins',
      to: 'cool_features#gmap_skins',
      as: :cool_features_gmap_skins

  # App Views
  get 'app_views/projects', to: 'app_views#projects', as: :app_views_projects
  get 'app_views/blog', to: 'app_views#blog', as: :app_views_blog
  get 'app_views/gallery', to: 'app_views#gallery', as: :app_views_gallery
  get 'app_views/forum_layout_general_view',
      to: 'app_views#forum_layout_general_view',
      as: :app_views_forum_layout_general_view
  get 'app_views/forum_layout_topic_view',
      to: 'app_views#forum_layout_topic_view',
      as: :app_views_forum_layout_topic_view
  get 'app_views/forum_layout_post_view',
      to: 'app_views#forum_layout_post_view',
      as: :app_views_forum_layout_post_view
  get 'app_views/profile', to: 'app_views#profile', as: :app_views_profile
  get 'app_views/timeline', to: 'app_views#timeline', as: :app_views_timeline
  get 'app_views/search_page',
      to: 'app_views#search_page',
      as: :app_views_search_page

  # E-Commerce
  get 'e_commerce/orders', to: 'e_commerce#orders', as: :e_commerce_orders
  get 'e_commerce/products_view',
      to: 'e_commerce#products_view',
      as: :e_commerce_products_view
  get 'e_commerce/products_detail',
      to: 'e_commerce#products_detail',
      as: :e_commerce_products_detail

  # Miscellaneous
  get 'miscellaneous/pricing_tables',
      to: 'miscellaneous#pricing_tables',
      as: :miscellaneous_pricing_tables
  get 'miscellaneous/invoice',
      to: 'miscellaneous#invoice',
      as: :miscellaneous_invoice
  get 'miscellaneous/login',
      to: 'miscellaneous#login',
      as: :miscellaneous_login
  get 'miscellaneous/register',
      to: 'miscellaneous#register',
      as: :miscellaneous_register
  get 'miscellaneous/forgot_password',
      to: 'miscellaneous#forgot_password',
      as: :miscellaneous_forgot_password
  get 'miscellaneous/locked_screen',
      to: 'miscellaneous#locked_screen',
      as: :miscellaneous_locked_screen
  get 'miscellaneous/error_404',
      to: 'miscellaneous#error_404',
      as: :miscellaneous_error_404
  get 'miscellaneous/error_500',
      to: 'miscellaneous#error_500',
      as: :miscellaneous_error_500
  get 'miscellaneous/blank_page',
      to: 'miscellaneous#blank_page',
      as: :miscellaneous_blank_page

  # Smart chat API
  get 'smart_chat_api/',
      to: 'smart_chat_api#index',
      as: :smart_chat_api

  # Misc methods
  get '/home/set_locale', to: 'home#set_locale', as: :home_set_locale

  # CK editor
  mount Ckeditor::Engine => '/ckeditor'
end

WB0573SK0/DEVELOPER/BS3/RubyOnRails/full/app/controllers/miscellaneous_controller.rb
class MiscellaneousController < ApplicationController
  skip_before_filter :authenticate_user!, only: [:register, :forgot_password]
  def pricing_tables
  end

  def invoice
  end

  def login
    @simulate_no_user = true
  end

  def register
    @simulate_no_user = true
  end

  def forgot_password
    @simulate_no_user = true
  end

  def locked_screen
    @simulate_no_user = true
    @lock_screen = true
  end

  def error_404
  end

  def error_500
  end

  def blank_page
  end
end

WB0573SK0/DEVELOPER/BS3/RubyOnRails/full/app/views/miscellaneous/blank_page.html.erb
<% content_for :ribbon do %>
  <!-- RIBBON -->
  <div id="ribbon">

  <span class="ribbon-button-alignment">
    <span id="refresh" class="btn btn-ribbon" data-action="resetWidgets" data-title="refresh"  rel="tooltip" data-placement="bottom" data-original-title="<i class='text-warning fa fa-warning'></i> Warning! This will reset all your widget settings." data-html="true">
      <i class="fa fa-refresh"></i>
    </span>
  </span>

    <!-- breadcrumb -->
    <ol class="breadcrumb">
      <li>Home</li><li>Miscellaneous</li><li>Blank Page</li>
    </ol>
    <!-- end breadcrumb -->

    <!-- You can also add more buttons to the
    ribbon for further usability

    Example below:

    <span class="ribbon-button-alignment pull-right">
    <span id="search" class="btn btn-ribbon hidden-xs" data-title="search"><i class="fa-grid"></i> Change Grid</span>
    <span id="add" class="btn btn-ribbon hidden-xs" data-title="add"><i class="fa-plus"></i> Add</span>
    <span id="search" class="btn btn-ribbon" data-title="search"><i class="fa-search"></i> <span class="hidden-mobile">Search</span></span>
    </span> -->

  </div>
  <!-- END RIBBON -->
<% end %>

<!-- MAIN CONTENT -->
<div id="content">

  <!-- row -->
  <div class="row">

    <!-- col -->
    <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
      <h1 class="page-title txt-color-blueDark">

        <!-- PAGE HEADER -->
        <i class="fa-fw fa fa-home"></i>
          Page Header
        <span>>
          Subtitle
        </span>
      </h1>
    </div>
    <!-- end col -->

    <!-- right side of the page with the sparkline graphs -->
    <!-- col -->
    <div class="col-xs-12 col-sm-5 col-md-5 col-lg-8">
      <!-- sparks -->
      <ul id="sparks">
        <li class="sparks-info">
          <h5> My Income <span class="txt-color-blue">$47,171</span></h5>
          <div class="sparkline txt-color-blue hidden-mobile hidden-md hidden-sm">
            1300, 1877, 2500, 2577, 2000, 2100, 3000, 2700, 3631, 2471, 2700, 3631, 2471
          </div>
        </li>
        <li class="sparks-info">
          <h5> Site Traffic <span class="txt-color-purple"><i class="fa fa-arrow-circle-up" data-rel="bootstrap-tooltip" title="Increased"></i>&nbsp;45%</span></h5>
          <div class="sparkline txt-color-purple hidden-mobile hidden-md hidden-sm">
            110,150,300,130,400,240,220,310,220,300, 270, 210
          </div>
        </li>
        <li class="sparks-info">
          <h5> Site Orders <span class="txt-color-greenDark"><i class="fa fa-shopping-cart"></i>&nbsp;2447</span></h5>
          <div class="sparkline txt-color-greenDark hidden-mobile hidden-md hidden-sm">
            110,150,300,130,400,240,220,310,220,300, 270, 210
          </div>
        </li>
      </ul>
      <!-- end sparks -->
    </div>
    <!-- end col -->

  </div>
  <!-- end row -->

  <!--
    The ID "widget-grid" will start to initialize all widgets below
    You do not need to use widgets if you dont want to. Simply remove
    the <section></section> and you can use wells or panels instead
    -->

  <!-- widget grid -->
  <section id="widget-grid" class="">

    <!-- row -->
    <div class="row">

      <!-- NEW WIDGET START -->
      <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

        <!-- Widget ID (each widget will need unique ID)-->
        <div class="jarviswidget" id="wid-id-0">
          <!-- widget options:
            usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">

            data-widget-colorbutton="false"
            data-widget-editbutton="false"
            data-widget-togglebutton="false"
            data-widget-deletebutton="false"
            data-widget-fullscreenbutton="false"
            data-widget-custombutton="false"
            data-widget-collapsed="true"
            data-widget-sortable="false"

          -->
          <header>
            <span class="widget-icon"> <i class="fa fa-comments"></i> </span>
            <h2>Widget Title </h2>

          </header>

          <!-- widget div-->
          <div>

            <!-- widget edit box -->
            <div class="jarviswidget-editbox">
              <!-- This area used as dropdown edit box -->
              <input class="form-control" type="text">
            </div>
            <!-- end widget edit box -->

            <!-- widget content -->
            <div class="widget-body">

              <!-- this is what the user will see -->

            </div>
            <!-- end widget content -->

          </div>
          <!-- end widget div -->

        </div>
        <!-- end widget -->

      </article>
      <!-- WIDGET END -->

    </div>

    <!-- end row -->

    <!-- row -->

    <div class="row">

      <!-- a blank row to get started -->
      <div class="col-sm-12">
        <!-- your contents here -->
      </div>

    </div>

    <!-- end row -->

  </section>
  <!-- end widget grid -->

</div>
<!-- END MAIN CONTENT -->

WB0573SK0/DEVELOPER/BS3/RubyOnRails/full/app/views/miscellaneous/error_500.html.erb
<% content_for :head do %>
  <!--[if IE 9]>
  <style>
    .error-text {
      color: #333 !important;
    }
  </style>
  <![endif]-->

<% end %>

<% content_for :ribbon do %>
  <!-- RIBBON -->
  <div id="ribbon">

  <span class="ribbon-button-alignment">
    <span id="refresh" class="btn btn-ribbon" data-action="resetWidgets" data-title="refresh"  rel="tooltip" data-placement="bottom" data-original-title="<i class='text-warning fa fa-warning'></i> Warning! This will reset all your widget settings." data-html="true">
      <i class="fa fa-refresh"></i>
    </span>
  </span>

    <!-- breadcrumb -->
    <ol class="breadcrumb">
      <li>Home</li><li>Miscellaneous</li><li>Error 500</li>
    </ol>
    <!-- end breadcrumb -->

    <!-- You can also add more buttons to the
    ribbon for further usability

    Example below:

    <span class="ribbon-button-alignment pull-right">
    <span id="search" class="btn btn-ribbon hidden-xs" data-title="search"><i class="fa-grid"></i> Change Grid</span>
    <span id="add" class="btn btn-ribbon hidden-xs" data-title="add"><i class="fa-plus"></i> Add</span>
    <span id="search" class="btn btn-ribbon" data-title="search"><i class="fa-search"></i> <span class="hidden-mobile">Search</span></span>
    </span> -->

  </div>
  <!-- END RIBBON -->
<% end %>


<!-- MAIN CONTENT -->
<div id="content">

  <!-- row -->
  <div class="row">

    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

      <div class="row">
        <div class="col-sm-12">
          <div class="text-center error-box">
            <h1 class="error-text tada animated"><i class="fa fa-times-circle text-danger error-icon-shadow"></i> Error 500</h1>
            <h2 class="font-xl"><strong>Oooops, Something went wrong!</strong></h2>
            <br />
            <p class="lead semi-bold">
              <strong>You have experienced a technical error. We apologize.</strong><br><br>
              <small>
                We are working hard to correct this issue. Please wait a few moments and try your search again. <br> In the meantime, check out whats new on SmartAdmin:
              </small>
            </p>
            <ul class="error-search text-left font-md">
                    <li><a href="javascript:void(0);"><small>Go to My Dashboard <i class="fa fa-arrow-right"></i></small></a></li>
                    <li><a href="javascript:void(0);"><small>Contact SmartAdmin IT Staff <i class="fa fa-mail-forward"></i></small></a></li>
                    <li><a href="javascript:void(0);"><small>Report error!</small></a></li>
                    <li><a href="javascript:void(0);"><small>Go back</small></a></li>
                </ul>
          </div>

        </div>

      </div>

    </div>

  </div>
  <!-- end row -->

</div>
<!-- END MAIN CONTENT -->

<% content_for :scripts do %>
  <script type="text/javascript">

    // DO NOT REMOVE : GLOBAL FUNCTIONS!

    $(document).ready(function() {

      $("#search-error").focus();

    })

  </script>
<% end %>

WB0573SK0/DEVELOPER/BS3/RubyOnRails/full/app/views/miscellaneous/forgot_password.html.erb
<% content_for :html_id, "extr-page" %>
<% content_for :body_class, "animated fadeInDown" %>
<% content_for :top_right do %>
  <span id="extr-page-header-space"> <span class="hidden-mobile hiddex-xs">Need an account?</span>
    <%= link_to 'Create account', miscellaneous_register_path, class: 'btn btn-danger' %>
  </span>
<% end %>
<!-- MAIN CONTENT -->
<div id="content" class="container">

  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-7 col-lg-8 hidden-xs hidden-sm">
      <h1 class="txt-color-red login-header-big">SmartAdmin</h1>
      <div class="hero">

        <div class="pull-left login-desc-box-l">
          <h4 class="paragraph-header">It's Okay to be Smart. Experience the simplicity of SmartAdmin, everywhere you go!</h4>
          <div class="login-app-icons">
            <a href="javascript:void(0);" class="btn btn-danger btn-sm">Frontend Template</a>
            <a href="javascript:void(0);" class="btn btn-danger btn-sm">Find out more</a>
          </div>
        </div>

        <%= image_tag 'demo/iphoneview.png', class: 'pull-right display-image', alt: '', style: 'width:210px' %>

      </div>

      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
          <h5 class="about-heading">About SmartAdmin - Are you up to date?</h5>
          <p>
            Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa.
          </p>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
          <h5 class="about-heading">Not just your average template!</h5>
          <p>
            Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi voluptatem accusantium!
          </p>
        </div>
      </div>

    </div>
    <div class="col-xs-12 col-sm-12 col-md-5 col-lg-4">
      <div class="well no-padding">
        <form action="login.html" id="login-form" class="smart-form client-form">
          <header>
            Forgot Password
          </header>

          <fieldset>

            <section>
              <label class="label">Enter your email address</label>
              <label class="input"> <i class="icon-append fa fa-envelope"></i>
                <input type="email" name="email">
                <b class="tooltip tooltip-top-right"><i class="fa fa-envelope txt-color-teal"></i> Please enter email address for password reset</b></label>
            </section>
            <section>
              <span class="timeline-seperator text-center text-primary"> <span class="font-sm">OR</span></span>
            </section>
            <section>
              <label class="label">Your Username</label>
              <label class="input"> <i class="icon-append fa fa-user"></i>
                <input type="text" name="username">
                <b class="tooltip tooltip-top-right"><i class="fa fa-user txt-color-teal"></i> Enter your username</b> </label>
              <div class="note">
                <a href="login.html">I remembered my password!</a>
              </div>
            </section>

          </fieldset>
          <footer>
            <button type="submit" class="btn btn-primary">
              <i class="fa fa-refresh"></i> Reset Password
            </button>
          </footer>
        </form>

      </div>

      <h5 class="text-center"> - Or sign in using -</h5>

              <ul class="list-inline text-center">
                <li>
                  <a href="javascript:void(0);" class="btn btn-primary btn-circle"><i class="fa fa-facebook"></i></a>
                </li>
                <li>
                  <a href="javascript:void(0);" class="btn btn-info btn-circle"><i class="fa fa-twitter"></i></a>
                </li>
                <li>
                  <a href="javascript:void(0);" class="btn btn-warning btn-circle"><i class="fa fa-linkedin"></i></a>
                </li>
              </ul>

    </div>
  </div>
</div>

WB0573SK0/DEVELOPER/BS3/RubyOnRails/full/app/views/miscellaneous/locked_screen.html.erb
<% content_for :html_id, "lock-page" %>
<!-- MAIN CONTENT -->

<form class="lockscreen animated flipInY" action="index.html">
  <div class="logo">
    <h1 class="semi-bold"><%= image_tag 'logo-o.png', alt: '' %> SmartAdmin</h1>
  </div>
  <div>
    <%= image_tag 'avatars/sunny-big.png', alt: '', width: '120', height: '120' %>
    <div>
      <h1><i class="fa fa-user fa-3x text-muted air air-top-right hidden-mobile"></i>John Doe <small><i class="fa fa-lock text-muted"></i> &nbsp;Locked</small></h1>
      <p class="text-muted">
        <a href="mailto:simmons@smartadmin">john.doe@smartadmin.com</a>
      </p>

      <div class="input-group">
        <input class="form-control" type="password" placeholder="Password">
        <div class="input-group-btn">
          <button class="btn btn-primary" type="submit">
            <i class="fa fa-key"></i>
          </button>
        </div>
      </div>
      <p class="no-margin margin-top-5">
        Logged as someone else? <a href="login.html"> Click here</a>
      </p>
    </div>

  </div>
  <p class="font-xs margin-top-5">
    Copyright SmartAdmin 2014-2020.

  </p>
</form>

WB0573SK0/DEVELOPER/BS3/RubyOnRails/full/app/views/miscellaneous/login.html.erb
<% content_for :html_id, "extr-page" %>
<% content_for :body_class, "animated fadeInDown" %>
<% content_for :top_right do %>
  <span id="extr-page-header-space"> <span class="hidden-mobile hiddex-xs">Need an account?</span> <a href="register.html" class="btn btn-danger">Create account</a> </span>
<% end %>
<!-- MAIN CONTENT -->
<div id="content" class="container">

  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-7 col-lg-8 hidden-xs hidden-sm">
      <h1 class="txt-color-red login-header-big">SmartAdmin</h1>
      <div class="hero">

        <div class="pull-left login-desc-box-l">
          <h4 class="paragraph-header">It's Okay to be Smart. Experience the simplicity of SmartAdmin, everywhere you go!</h4>
          <div class="login-app-icons">
            <a href="javascript:void(0);" class="btn btn-danger btn-sm">Frontend Template</a>
            <a href="javascript:void(0);" class="btn btn-danger btn-sm">Find out more</a>
          </div>
        </div>

        <%= image_tag 'demo/iphoneview.png', class: 'pull-right display-image', alt: '', style: 'width:210px' %>

      </div>

      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
          <h5 class="about-heading">About SmartAdmin - Are you up to date?</h5>
          <p>
            Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa.
          </p>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
          <h5 class="about-heading">Not just your average template!</h5>
          <p>
            Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi voluptatem accusantium!
          </p>
        </div>
      </div>

    </div>
    <div class="col-xs-12 col-sm-12 col-md-5 col-lg-4">
      <div class="well no-padding">
        <form action="index.html" id="login-form" class="smart-form client-form">
          <header>
            Sign In
          </header>

          <fieldset>

            <section>
              <label class="label">E-mail</label>
              <label class="input"> <i class="icon-append fa fa-user"></i>
                <input type="email" name="email">
                <b class="tooltip tooltip-top-right"><i class="fa fa-user txt-color-teal"></i> Please enter email address/username</b></label>
            </section>

            <section>
              <label class="label">Password</label>
              <label class="input"> <i class="icon-append fa fa-lock"></i>
                <input type="password" name="password">
                <b class="tooltip tooltip-top-right"><i class="fa fa-lock txt-color-teal"></i> Enter your password</b> </label>
              <div class="note">
                <a href="forgotpassword.html">Forgot password?</a>
              </div>
            </section>

            <section>
              <label class="checkbox">
                <input type="checkbox" name="remember" checked="">
                <i></i>Stay signed in</label>
            </section>
          </fieldset>
          <footer>
            <button type="submit" class="btn btn-primary">
              Sign in
            </button>
          </footer>
        </form>

      </div>

      <h5 class="text-center"> - Or sign in using -</h5>

        <ul class="list-inline text-center">
          <li>
            <a href="javascript:void(0);" class="btn btn-primary btn-circle"><i class="fa fa-facebook"></i></a>
          </li>
          <li>
            <a href="javascript:void(0);" class="btn btn-info btn-circle"><i class="fa fa-twitter"></i></a>
          </li>
          <li>
            <a href="javascript:void(0);" class="btn btn-warning btn-circle"><i class="fa fa-linkedin"></i></a>
          </li>
        </ul>

    </div>
  </div>
</div>


<% content_for :scripts do %>
  <script type="text/javascript">
    runAllForms();

    $(function() {
      // Validation
      $("#login-form").validate({
        // Rules for form validation
        rules : {
          email : {
            required : true,
            email : true
          },
          password : {
            required : true,
            minlength : 3,
            maxlength : 20
          }
        },

        // Messages for form validation
        messages : {
          email : {
            required : 'Please enter your email address',
            email : 'Please enter a VALID email address'
          },
          password : {
            required : 'Please enter your password'
          }
        },

        // Do not change code below
        errorPlacement : function(error, element) {
          error.insertAfter(element.parent());
        }
      });
    });
  </script>
<% end %>