WB0573SK0/DEVELOPER/BS3/RubyOnRails/full/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'dashboard#analytics'
  get 'dashboards/dashboard-social',
      to: 'dashboard#social',
      as: :dashboard_social

  # Smartadmin intel
  get 'smartadmin_intel/app_layouts',
      to: 'smartadmin_intel#app_layouts',
      as: :smartadmin_intel_app_layouts
  get 'smartadmin_intel/app_settings',
      to: 'smartadmin_intel#app_settings',
      as: :smartadmin_intel_app_settings
  get 'smartadmin_intel/prebuilt_skins',
      to: 'smartadmin_intel#prebuilt_skins',
      as: :smartadmin_intel_prebuilt_skins
  get 'outlook/inbox', to: 'outlook#inbox', as: :outlook_inbox

  # AJAX
  get 'ajax/email_compose', to: 'ajax#email_compose', as: :ajax_email_compose
  get 'ajax/email_list', to: 'ajax#email_list', as: :ajax_email_list
  get 'ajax/email_opened', to: 'ajax#email_opened', as: :ajax_email_opened
  get 'ajax/email_reply', to: 'ajax#email_reply', as: :ajax_email_reply
  get 'ajax/demo_widget', to: 'ajax#demo_widget', as: :ajax_demo_widget
  get 'ajax/data_list.json', to: 'ajax#data_list', as: :ajax_data_list
  get 'ajax/notify_mail', to: 'ajax#notify_mail', as: :ajax_notify_mail
  get 'ajax/notify_notifications',
      to: 'ajax#notify_notifications',
      as: :ajax_notify_notifications
  get 'ajax/notify_tasks', to: 'ajax#notify_tasks', as: :ajax_notify_tasks

  # Graphs
  get 'graphs/flot_chart', to: 'graphs#flot_chart', as: :graphs_flot_chart
  get 'graphs/morris_charts',
      to: 'graphs#morris_charts',
      as: :graphs_morris_charts
  get 'graphs/sparklines', to: 'graphs#sparklines', as: :graphs_sparklines
  get 'graphs/easy_pie_charts',
      to: 'graphs#easy_pie_charts',
      as: :graphs_easy_pie_charts
  get 'graphs/dygraphs', to: 'graphs#dygraphs', as: :graphs_dygraphs
  get 'graphs/chart_js', to: 'graphs#chart_js', as: :graphs_chart_js
  get 'graphs/highchart_table',
      to: 'graphs#highchart_table',
      as: :graphs_highchart_table

  # Tables
  get 'tables/normal_tables',
      to: 'tables#normal_tables',
      as: :tables_normal_tables
  get 'tables/data_tables', to: 'tables#data_tables', as: :tables_data_tables
  get 'tables/jquery_grid', to: 'tables#jquery_grid', as: :tables_jquery_grid

  # Forms
  get 'forms/smart_form_elements',
      to: 'forms#smart_form_elements',
      as: :forms_smart_form_elements
  get 'forms/smart_form_layouts',
      to: 'forms#smart_form_layouts',
      as: :forms_smart_form_layouts
  get 'forms/smart_form_validations',
      to: 'forms#smart_form_validations',
      as: :forms_smart_form_validations
  get 'forms/bootstrap_form_elements',
      to: 'forms#bootstrap_form_elements',
      as: :forms_bootstrap_form_elements
  get 'forms/bootstrap_form_validation',
      to: 'forms#bootstrap_form_validation',
      as: :forms_bootstrap_form_validation
  get 'forms/form_plugins', to: 'forms#form_plugins', as: :forms_form_plugins
  get 'forms/wizards', to: 'forms#wizards', as: :forms_wizards
  get 'forms/bootstrap_editors',
      to: 'forms#bootstrap_editors',
      as: :forms_bootstrap_editors
  get 'forms/dropzone', to: 'forms#dropzone', as: :forms_dropzone
  get 'forms/image_cropping',
      to: 'forms#image_cropping',
      as: :forms_image_cropping
  get 'forms/ck_editor', to: 'forms#ck_editor', as: :forms_ck_editor

  # UI Elements
  get 'ui_elements/general_elements',
      to: 'ui_elements#general_elements',
      as: :ui_elements_general_elements
  get 'ui_elements/buttons', to: 'ui_elements#buttons', as: :ui_elements_buttons
  get 'ui_elements/icons/font_awesome',
      to: 'ui_elements#icons_font_awesome',
      as: :ui_elements_icons_font_awesome
  get 'ui_elements/icons/glyph_icons',
      to: 'ui_elements#icons_glyph_icons',
      as: :ui_elements_icons_glyph_icons
  get 'ui_elements/icons/flags',
      to: 'ui_elements#icons_flags',
      as: :ui_elements_icons_flags
  get 'ui_elements/grid', to: 'ui_elements#grid', as: :ui_elements_grid
  get 'ui_elements/tree_view',
      to: 'ui_elements#tree_view',
      as: :ui_elements_tree_view
  get 'ui_elements/nestable_lists',
      to: 'ui_elements#nestable_lists',
      as: :ui_elements_nestable_lists
  get 'ui_elements/jquery_ui',
      to: 'ui_elements#jquery_ui',
      as: :ui_elements_jquery_ui
  get 'ui_elements/typography',
      to: 'ui_elements#typography',
      as: :ui_elements_typography

  # Widgets
  get 'widgets/', to: 'widgets#index', as: :widgets

  # Cool Features
  get 'cool_features/calendar',
      to: 'cool_features#calendar',
      as: :cool_features_calendar
  get 'cool_features/gmap_skins',
      to: 'cool_features#gmap_skins',
      as: :cool_features_gmap_skins

  # App Views
  get 'app_views/projects', to: 'app_views#projects', as: :app_views_projects
  get 'app_views/blog', to: 'app_views#blog', as: :app_views_blog
  get 'app_views/gallery', to: 'app_views#gallery', as: :app_views_gallery
  get 'app_views/forum_layout_general_view',
      to: 'app_views#forum_layout_general_view',
      as: :app_views_forum_layout_general_view
  get 'app_views/forum_layout_topic_view',
      to: 'app_views#forum_layout_topic_view',
      as: :app_views_forum_layout_topic_view
  get 'app_views/forum_layout_post_view',
      to: 'app_views#forum_layout_post_view',
      as: :app_views_forum_layout_post_view
  get 'app_views/profile', to: 'app_views#profile', as: :app_views_profile
  get 'app_views/timeline', to: 'app_views#timeline', as: :app_views_timeline
  get 'app_views/search_page',
      to: 'app_views#search_page',
      as: :app_views_search_page

  # E-Commerce
  get 'e_commerce/orders', to: 'e_commerce#orders', as: :e_commerce_orders
  get 'e_commerce/products_view',
      to: 'e_commerce#products_view',
      as: :e_commerce_products_view
  get 'e_commerce/products_detail',
      to: 'e_commerce#products_detail',
      as: :e_commerce_products_detail

  # Miscellaneous
  get 'miscellaneous/pricing_tables',
      to: 'miscellaneous#pricing_tables',
      as: :miscellaneous_pricing_tables
  get 'miscellaneous/invoice',
      to: 'miscellaneous#invoice',
      as: :miscellaneous_invoice
  get 'miscellaneous/login',
      to: 'miscellaneous#login',
      as: :miscellaneous_login
  get 'miscellaneous/register',
      to: 'miscellaneous#register',
      as: :miscellaneous_register
  get 'miscellaneous/forgot_password',
      to: 'miscellaneous#forgot_password',
      as: :miscellaneous_forgot_password
  get 'miscellaneous/locked_screen',
      to: 'miscellaneous#locked_screen',
      as: :miscellaneous_locked_screen
  get 'miscellaneous/error_404',
      to: 'miscellaneous#error_404',
      as: :miscellaneous_error_404
  get 'miscellaneous/error_500',
      to: 'miscellaneous#error_500',
      as: :miscellaneous_error_500
  get 'miscellaneous/blank_page',
      to: 'miscellaneous#blank_page',
      as: :miscellaneous_blank_page

  # Smart chat API
  get 'smart_chat_api/',
      to: 'smart_chat_api#index',
      as: :smart_chat_api

  # Misc methods
  get '/home/set_locale', to: 'home#set_locale', as: :home_set_locale

  # CK editor
  mount Ckeditor::Engine => '/ckeditor'
end

WB0573SK0/DEVELOPER/BS3/RubyOnRails/full/app/controllers/ajax_controller.rb
# AJAX helpers
class AjaxController < ApplicationController
  layout false

  def email_list
  end

  def email_compose
  end

  def email_opened
  end

  def email_reply
  end

  def demo_widget
  end

  def data_list
  end

  def notify_mail
  end

  def notify_notifications
  end

  def notify_tasks
  end
end

WB0573SK0/DEVELOPER/BS3/RubyOnRails/full/app/views/ajax/demo_widget.html.erb
<p class="alert alert-info">
	This widget is fetching data from an external source with the use of code <code>data-widget-load="<i class="text-primary">[data source]</i>"</code>. Turn on auto refresh by adding the timer like so <code>data-widget-refresh="15"</code> , which will refresh the widget and fetch the data every 15 seconds.
</p>
<!-- dummy file -->
<div class="row">
	<div class="col-sm-7">
		<code>data-widget-load="<i class="text-primary">ajax/demo_widget</i>"</code>
	</div>
	<div class="col-sm-5 text-right">
		<div class="jarviswidget-timestamp no-margin"></div>
	</div>
</div>

<div id="flotcontainer" style="height:200px; width:100%;"></div>


	<script type="text/javascript">

		/*
		* RUN PAGE GRAPHS
		*/
	
		// Load FLOAT dependencies (related to page)
		loadScript("<%= javascript_path 'plugin/flot/jquery.flot.cust.js' %>", loadFlotResize);
	
		function loadFlotResize() {
			loadScript("<%= javascript_path 'plugin/flot/jquery.flot.resize.js' %>", loadFlotToolTip);
		}
	
		function loadFlotToolTip() {
			loadScript("<%= javascript_path 'plugin/flot/jquery.flot.tooltip.min.js' %>", generateRandomFlot);
		}

		function generateRandomFlot(){

		    function GenerateSeries(added){
		        var data = [];
		        var start = 100 + added;
		        var end = 500 + added;
		 
		        for(i=1;i<=20;i++){        
		            var d = Math.floor(Math.random() * (end - start + 1) + start);        
		            data.push([i, d]);
		            start++;
		            end++;
		        }
		 
		        return data;
		    }
		 
		    var data1 = GenerateSeries(0);
		    var data2 = GenerateSeries(10);    
		 
		    var markings = [
		        { xaxis: { from: 1, to: 2 }, color: "#E8E8E8" },
		        { xaxis: { from: 4, to: 5 }, color: "#E8E8E8" },
		        { xaxis: { from: 7, to: 8 }, color: "#E8E8E8" },
		        { xaxis: { from: 10, to: 11 }, color: "#E8E8E8" },
		        { xaxis: { from: 13, to: 14 }, color: "#E8E8E8" },
		        { xaxis: { from: 16, to: 17 }, color: "#E8E8E8" },
		        { xaxis: { from: 19, to: 20 }, color: "#E8E8E8" }
		 
		    ];
		 
		    var options = {            
		             series: {
		                lines: { show: true, lineWidth: 3 },
		                shadowSize: 0
		            },
		            grid: {
		                markings: markings,
		                backgroundColor: { colors: ["#D1D1D1", "#7A7A7A"] }
		            }      
		    };
		 
		    $.plot($("#flotcontainer"),
		        [
		            {data:data1},
		            {data:data2}
		        ], options
		    );

		}



	</script>

WB0573SK0/DEVELOPER/BS3/RubyOnRails/full/app/views/ajax/email_compose.html.erb
<h2 class="email-open-header">
	Compose New Email <span class="label txt-color-white">DRAFT</span>
	<a href="javascript:void(0);" rel="tooltip" data-placement="left" data-original-title="Print" class="txt-color-darken pull-right"><i class="fa fa-print"></i></a>	
</h2>

<form enctype="multipart/form-data" action="dummy.php" method="POST" class="form-horizontal" id="email-compose-form">

	<div class="inbox-info-bar no-padding">
		<div class="row">
			<div class="form-group">
				<label class="control-label col-md-1"><strong>To</strong></label>
				<div class="col-md-11">
					<select multiple style="width:100%" class="select2" data-select-search="true">
						<option value="sunny.orlaf@smartadmin.com">sadi.orlaf@smartadmin.com</option>
						<option value="rachael.hawi@smartadmin.com">rachael.hawi@smartadmin.com</option>
						<option value="michael.safiel@smartadmin.com">michael.safiel@smartadmin.com</option>
						<option value="alex.jones@infowars.com">alex.jones@infowars.com</option>
						<option value="oruf.matalla@gmail.com">oruf.matalla@gmail.com</option>
						<option value="hr@smartadmin.com">hr@smartadmin.com</option>
						<option value="IT@smartadmin.com" selected="selected">IT@smartadmin.com</option>
					</select>
					<em><a href="javascript:void(0);" class="show-next" rel="tooltip" data-placement="bottom" data-original-title="Carbon Copy">CC</a></em>
				</div>
			</div>
		</div>	
	</div>
	
	<div class="inbox-info-bar no-padding hidden">
		<div class="row">
			<div class="form-group">
				<label class="control-label col-md-1"><strong>CC</strong></label>
				<div class="col-md-11">
					<select multiple style="width:100%" class="select2" data-select-search="true">
						<option value="sunny.orlaf@smartadmin.com" selected="selected">sunny.orlaf@smartadmin.com</option>
						<option value="rachael.hawi@smartadmin.com" selected="selected">rachael.hawi@smartadmin.com</option>
						<option value="michael.safiel@smartadmin.com">michael.safiel@smartadmin.com</option>
						<option value="alex.jones@infowars.com">alex.jones@infowars.com</option>
						<option value="oruf.matalla@gmail.com">oruf.matalla@gmail.com</option>
						<option value="hr@smartadmin.com">hr@smartadmin.com</option>
						<option value="IT@smartadmin.com">IT@smartadmin.com</option>
					</select>
					<em><a href="javascript:void(0);" class="show-next" rel="tooltip" data-placement="bottom" data-original-title="Blind Carbon Copy">BCC</a></em>
				</div>
			</div>
		</div>	
	</div>

	<div class="inbox-info-bar no-padding hidden">
		<div class="row">
			<div class="form-group">
				<label class="control-label col-md-1"><strong>BCC</strong></label>
				<div class="col-md-11">
					<select multiple style="width:100%" class="select2" data-select-search="true">
						<option value="sunny.orlaf@smartadmin.com">sunny.orlaf@smartadmin.com</option>
						<option value="rachael.hawi@smartadmin.com">rachael.hawi@smartadmin.com</option>
						<option value="michael.safiel@smartadmin.com">michael.safiel@smartadmin.com</option>
						<option value="alex.jones@infowars.com">alex.jones@infowars.com</option>
						<option value="oruf.matalla@gmail.com">oruf.matalla@gmail.com</option>
						<option value="hr@smartadmin.com">hr@smartadmin.com</option>
						<option value="IT@smartadmin.com">IT@smartadmin.com</option>
					</select>
				</div>
			</div>
		</div>	
	</div>
	
	<div class="inbox-info-bar no-padding">
		<div class="row">
			<div class="form-group">
				<label class="control-label col-md-1"><strong>Subject</strong></label>
				<div class="col-md-11">
					<input class="form-control" placeholder="Email Subject" type="text">
					<em><a href="javascript:void(0);" class="show-next" rel="tooltip" data-placement="bottom" data-original-title="Attachments"><i class="fa fa-paperclip fa-lg"></i></a></em>
				</div>
			</div>
		</div>	
	</div>

	<div class="inbox-info-bar no-padding hidden">
		<div class="row">
			<div class="form-group">
				<label class="control-label col-md-1"><strong>Attachments</strong></label>
				<div class="col-md-11">
					<input class="form-control fileinput" type="file" multiple="multiple">
				</div>
			</div>
		</div>	
	</div>
	
	<div class="inbox-message no-padding">
	
		<div id="emailbody">
			
				<br><br><br><br><br>Thanks,<br><strong>John Doe</strong><br><br><small>CEO - SmartAdmin <br> 231 Ajax Rd, Detroit MI - 48212, USA<br><i class="fa fa-phone"> (313) 647 4761</i></small><br><%= image_tag 'logo-blacknwhite.png', height: '20', width: 'auto', style: 'margin-top:7px; padding-right:9px; border-right:1px dotted #9B9B9B;' %>
		</div>	
	</div>
	
	<div class="inbox-compose-footer">

	<button class="btn btn-danger" type="button">
		Disregard
	</button>
		
	<button class="btn btn-info" type="button">
		Draft
	</button>

	<button data-loading-text="&lt;i class='fa fa-refresh fa-spin'&gt;&lt;/i&gt; &nbsp; Sending..." class="btn btn-primary pull-right" type="button" id="send">
		Send <i class="fa fa-arrow-circle-right fa-lg"></i>
	</button>


	</div>

</form>

<div class="email-infobox">

	<div class="well well-sm well-light">
		<h5>Related Invoice</h5>
		<ul class="list-unstyled">
			<li>
				<i class="fa fa-file fa-fw text-success"></i><a href="javascript:void(0);"> #4831 - Paid</a>
			</li>
			<li>
				<i class="fa fa-file fa-fw text-danger"></i><a href="javascript:void(0);"><strong> #4835 - Unpaid</strong></a>
			</li>
		</ul>


	</div>

	<div class="well well-sm well-light">
		<h5>Upcoming Meetings</h5>
		
		<p>
			<span class="label label-success"><i class="fa fa-check"></i> <strike>Agenda Review @ 10 AM</strike> </span>
		</p>

		<p>
			<span class="label label-primary"><i class="fa fa-clock-o"></i> Client Meeting @ 2:30 PM</span>
		</p>

		<p>
			<span class="label label-warning"><i class="fa fa-clock-o"></i> Salary Review @ 4:00 PM</span>
		</p>		
	</div>	

	<ul class="list-inline">
		<li><%= image_tag 'avatars/5.png', alt: 'me', width: '30px' %></li>
		<li><%= image_tag 'avatars/3.png', alt: 'me', width: '30px' %></li>
		<li><%= image_tag 'avatars/sunny.png', alt: 'me', width: '30px' %></li>
		<li><a href="javascript:void(0);">1 more</a></li>
	</ul>

</div>

<script type="text/javascript">
	
	// DO NOT REMOVE : GLOBAL FUNCTIONS!

	runAllForms();

	 // PAGE RELATED SCRIPTS

	$(".table-wrap [rel=tooltip]").tooltip();



    $('#emailbody').summernote({
        height: 250,
        focus: false,
        tabsize: 2
    });


	$(".show-next").click(function () {
	    $this = $(this);
	    $this.hide();
	    $this.parent().parent().parent().parent().parent().next().removeClass("hidden");
	})

	 $("#send").click(function () {

	    var $btn = $(this);
	    $btn.button('loading');

	    // wait for animation to finish and execute send script
	    setTimeout(function () {
	        //Insert send script here


	        // Load inbox once send is complete
	
			loadURL("<%= ajax_email_list_path %>", $('#inbox-content > .table-wrap'))


	    }, 1000); // how long do you want the delay to be? 
	});
	
	
</script>

WB0573SK0/DEVELOPER/BS3/RubyOnRails/full/app/views/ajax/email_opened.html.erb
<h2 class="email-open-header">
	Re: Timelogs of last client <span class="label txt-color-white">inbox</span>
	<a href="javascript:void(0);" rel="tooltip" data-placement="left" data-original-title="Print" class="txt-color-darken pull-right"><i class="fa fa-print"></i></a>	
</h2>

<div class="inbox-info-bar">
	<div class="row">
		<div class="col-sm-9">
      <%= image_tag 'avatars/5.png', alt: 'me', class: 'away' %>
			<strong>Sadi Orlaf</strong>
			<span class="hidden-mobile">&lt;sadi.orlaf@smartadmin.com&gt;to <strong>me</strong> on <i>12:10AM, 12 March 2013</i></span> 
		</div>
		<div class="col-sm-3 text-right">
			
			<div class="btn-group text-left">
				<button class="btn btn-primary btn-sm replythis">
					<i class="fa fa-reply"></i> Reply
				</button>
				<button class="btn btn-primary btn-sm dropdown-toggle" data-toggle="dropdown">
					<i class="fa fa-angle-down"></i>
				</button>
				<ul class="dropdown-menu pull-right">
					<li>
						<a href="javascript:void(0);" class="replythis"><i class="fa fa-reply"></i> Reply</a>
					</li>
					<li>
						<a href="javascript:void(0);" class="replythis"><i class="fa fa-mail-forward"></i> Forward</a>
					</li>
					<li>
						<a href="javascript:void(0);"><i class="fa fa-print"></i> Print</a>
					</li>
					<li class="divider"></li>
					<li>
						<a href="javascript:void(0);"><i class="fa fa-ban"></i> Mark as spam!</a>
					</li>
					<li>
						<a href="javascript:void(0);"><i class="fa fa-trash-o"></i> Delete forever</a>
					</li>
				</ul>
			</div>

		</div>
	</div>
</div>

<div class="inbox-message">
	<p>
		Hey James,
	</p>
	<p>
		Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.
	</p>	
	
	<p>
		Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit. <i class="fa fa-smile-o"></i> 
	</p>
	
	<br>
	<br>
	Thanks,<br> 
	<strong>Sadi Orlaf</strong>
	<br>
	<br>
	<small>
		General Manager - Finance Department <br> 
		231 Ajax Rd, Detroit MI - 48212, USA
		<br>
		<i class="fa fa-phone"> (313) 647 6471</i> 

	</small>
	<br>	
  <%= image_tag 'logo-blacknwhite.png', height: '20', width: 'auto', style: 'margin-top:7px; padding-right:9px; border-right:1px dotted #9B9B9B;' %>
</div>

<div class="inbox-download">
	2 attachment(s) — <a href="javascript:void(0);"> Download all attachments</a> 
	
	<ul class="inbox-download-list">
		<li>
			<div class="well well-sm">
				<span>
          <%= image_tag 'demo/sample.jpg' %>
				</span>
				<br>
				<strong>rocketlaunch.jpg</strong> 
				<br>
				400 kb 
				<br> 
				<a href="javascript:void(0);"> Download</a>  | <a href="javascript:void(0);"> View</a>
			</div>
		</li>
		<li>
			<div class="well well-sm">
				<span>
					<i class="fa fa-file"></i>
				</span>
				
				<br>
				<strong>timelogs.xsl</strong> 
				<br>
				1.3 mb 
				<br> 
				<a href="javascript:void(0);"> Download</a> | <a href="javascript:void(0);"> Share</a>
			</div>
		</li>
	</ul>
</div>

<div class="email-infobox">

	<div class="well well-sm well-light">
		<h5>Related Invoice</h5>
		<ul class="list-unstyled">
			<li>
				<i class="fa fa-file fa-fw text-success"></i><a href="javascript:void(0);"> #4831 - Paid</a>
			</li>
			<li>
				<i class="fa fa-file fa-fw text-danger"></i><a href="javascript:void(0);"><strong> #4835 - Unpaid</strong></a>
			</li>
		</ul>


	</div>

	<div class="well well-sm well-light">
		<h5>Upcoming Meetings</h5>
		
		<p>
			<span class="label label-success"><i class="fa fa-check"></i> <strike>Agenda Review @ 10 AM</strike> </span>
		</p>

		<p>
			<span class="label label-primary"><i class="fa fa-clock-o"></i> Client Meeting @ 2:30 PM</span>
		</p>

		<p>
			<span class="label label-warning"><i class="fa fa-clock-o"></i> Salary Review @ 4:00 PM</span>
		</p>		
	</div>	

	<ul class="list-inline">
		<li><%= image_tag 'avatars/5.png', alt: 'me', width: '30px' %></li>
		<li><%= image_tag 'avatars/3.png', alt: 'me', width: '30px' %></li>
		<li><%= image_tag 'avatars/sunny.png', alt: 'me', width: '30px' %></li>
		<li><a href="javascript:void(0);">1 more</a></li>
	</ul>

</div>

<script type="text/javascript">
	
	// DO NOT REMOVE : GLOBAL FUNCTIONS!
	//pageSetUp();
	
	// PAGE RELATED SCRIPTS
	
	$(".table-wrap [rel=tooltip]").tooltip();

	$(".replythis").click(function(){
		loadURL("<%= ajax_email_reply_path %>", $('#inbox-content > .table-wrap'));
	})
	
</script>

WB0573SK0/DEVELOPER/BS3/RubyOnRails/full/app/views/ajax/notify_mail.html.erb
<ul class="notification-body">
	<li>
		<span class="unread">
			<a href="javascript:void(0);" class="msg">
				<%= image_tag 'avatars/4.png', alt: '', class: 'air air-top-left margin-top-5', width: '40', height: '40' %>
				<span class="from">John Doe <i class="icon-paperclip"></i></span>
				<time>2 minutes ago</time>
				<span class="subject">Msed quia non numquam eius modi tempora</span>
				<span class="msg-body">Hello again and thanks for being a part of the newsletter. </span>
			</a>
		</span>
	</li>
	<li>
		<span>
			<a href="javascript:void(0);" class="msg">
				<%= image_tag 'avatars/female.png', alt: '', class: 'air air-top-left margin-top-5', width: '40', height: '40' %>
				<span class="from">Sonya Birthday</span>
				<time>Thursday, September 19th</time>
				<span class="subject">Incidunt ut labor</span>
				<span class="msg-body">sed quia non numquam eius modi tempora incidunt ut labor</span>
			</a>
		</span>
	</li>
	<li>
		<span>
			<a href="javascript:void(0);" class="msg">
				<%= image_tag 'avatars/1.png', alt: '', class: 'air air-top-left margin-top-5', width: '40', height: '40' %>
				<span class="from">Cristina Algera</span>
				<time>Sunday, September 15th</time>
				<span class="subject">Best-Selling Teethers</span>
				<span class="msg-body"> ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?</span>
			</a>
		</span>
	</li>
	<li>
		<span>
			<a href="javascript:void(0);" class="msg">
				<%= image_tag 'avatars/male.png', alt: '', class: 'air air-top-left margin-top-5', width: '40', height: '40' %>
				<span class="from">Lam Tampora</span>
				<time>Saturday, September 14th</time>
				<span class="subject">Deadline due date</span>
				<span class="msg-body">imus qui blanditiis praesentium voluptatum deleniti atque corrup</span>
			</a>
		</span>
	</li>
	<li>
		<span class="unread">
			<a href="javascript:void(0);" class="msg">
				<%= image_tag 'avatars/sunny.png', alt: '', class: 'air air-top-left margin-top-5', width: '40', height: '40' %>
				<span class="from">Project approved! <i class="icon-paperclip"></i></span>
				<time>September 14th</time>
				<span class="subject">Et harum quidem rerum facilis est et expedita distinctio</span>
				<span class="msg-body">...</span>
			</a>
		</span>
	</li>
	<li>
		<span>
			<a href="javascript:void(0);" class="msg">
				<%= image_tag 'avatars/male.png', alt: '', class: 'air air-top-left margin-top-5', width: '40', height: '40' %>
				<span class="from">JEFF, me</span>
				<time>Friday, September 13th</time>
				<span class="subject">Bugs fixed! </span>
				<span class="msg-body">Nam libero tempore, cum soluta nobis est eligendi optio cumque</span>
			</a>
		</span>
	</li>
</ul>